// because the API has limited request
// data from https://free-to-play-games-database.p.rapidapi.com/api/games
import { GamesInfo } from "./types";

export const gamesArr: GamesInfo[] = [
  {
    id: 540,
    title: "Overwatch 2",
    thumbnail: "https://www.freetogame.com/g/540/thumbnail.jpg",
    short_description:
      "A hero-focused first-person team shooter from Blizzard Entertainment.",
    game_url: "https://www.freetogame.com/open/overwatch-2",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Activision Blizzard",
    developer: "Blizzard Entertainment",
    release_date: "2022-10-04",
    freetogame_profile_url: "https://www.freetogame.com/overwatch-2",
  },
  {
    id: 521,
    title: "Diablo Immortal",
    thumbnail: "https://www.freetogame.com/g/521/thumbnail.jpg",
    short_description:
      "Built for mobile and also released on PC, Diablo Immortal fills in the gaps between Diablo II and III in an MMOARPG environment.",
    game_url: "https://www.freetogame.com/open/diablo-immortal",
    genre: "MMOARPG",
    platform: "PC (Windows)",
    publisher: "Blizzard Entertainment",
    developer: "Blizzard Entertainment",
    release_date: "2022-06-02",
    freetogame_profile_url: "https://www.freetogame.com/diablo-immortal",
  },
  {
    id: 517,
    title: "Lost Ark",
    thumbnail: "https://www.freetogame.com/g/517/thumbnail.jpg",
    short_description:
      "Smilegate’s free-to-play multiplayer ARPG is a massive adventure filled with lands waiting to be explored, people waiting to be met, and an ancient evil waiting to be destroyed.",
    game_url: "https://www.freetogame.com/open/lost-ark",
    genre: "ARPG",
    platform: "PC (Windows)",
    publisher: "Amazon Games",
    developer: "Smilegate RPG",
    release_date: "2022-02-11",
    freetogame_profile_url: "https://www.freetogame.com/lost-ark",
  },
  {
    id: 516,
    title: "PUBG: BATTLEGROUNDS",
    thumbnail: "https://www.freetogame.com/g/516/thumbnail.jpg",
    short_description:
      "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
    game_url: "https://www.freetogame.com/open/pubg",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "KRAFTON, Inc.",
    developer: "KRAFTON, Inc.",
    release_date: "2022-01-12",
    freetogame_profile_url: "https://www.freetogame.com/pubg",
  },
  {
    id: 508,
    title: "Enlisted",
    thumbnail: "https://www.freetogame.com/g/508/thumbnail.jpg",
    short_description:
      "Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ",
    game_url: "https://www.freetogame.com/open/enlisted",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Gaijin Entertainment",
    developer: "Darkflow Software",
    release_date: "2021-04-08",
    freetogame_profile_url: "https://www.freetogame.com/enlisted",
  },
  {
    id: 345,
    title: "Forge of Empires",
    thumbnail: "https://www.freetogame.com/g/345/thumbnail.jpg",
    short_description:
      "A free to play 2D browser-based online strategy game, become the leader and raise your city.",
    game_url: "https://www.freetogame.com/open/forge-of-empires",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "InnoGames",
    developer: "InnoGames",
    release_date: "2012-04-17",
    freetogame_profile_url: "https://www.freetogame.com/forge-of-empires",
  },
  {
    id: 475,
    title: "Genshin Impact",
    thumbnail: "https://www.freetogame.com/g/475/thumbnail.jpg",
    short_description:
      "If you’ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you’re going to want to check out miHoYo’s Genshin Impact.",
    game_url: "https://www.freetogame.com/open/genshin-impact",
    genre: "Action RPG",
    platform: "PC (Windows)",
    publisher: "miHoYo",
    developer: "miHoYo",
    release_date: "2020-09-28",
    freetogame_profile_url: "https://www.freetogame.com/genshin-impact",
  },
  {
    id: 523,
    title: "Fall Guys",
    thumbnail: "https://www.freetogame.com/g/523/thumbnail.jpg",
    short_description:
      "Play the most competitive massively multiplayer party royale game featuring beans ever for free on a variety of platforms. ",
    game_url: "https://www.freetogame.com/open/fall-guys",
    genre: "Battle Royale",
    platform: "PC (Windows)",
    publisher: "Mediatonic",
    developer: "Mediatonic",
    release_date: "2020-08-04",
    freetogame_profile_url: "https://www.freetogame.com/fall-guys",
  },
  {
    id: 340,
    title: "Game Of Thrones Winter Is Coming",
    thumbnail: "https://www.freetogame.com/g/340/thumbnail.jpg",
    short_description:
      "A free-to-play browser-based RTS based on the George R.R. Martin novels and popular HBO series.",
    game_url:
      "https://www.freetogame.com/open/game-of-thrones-winter-is-coming",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "GTArcade",
    developer: "YOOZOO Games ",
    release_date: "2019-11-14",
    freetogame_profile_url:
      "https://www.freetogame.com/game-of-thrones-winter-is-coming",
  },
  {
    id: 347,
    title: "Elvenar",
    thumbnail: "https://www.freetogame.com/g/347/thumbnail.jpg",
    short_description:
      "A browser based city-building strategy MMO set in the fantasy world of Elvenar.",
    game_url: "https://www.freetogame.com/open/elvenar",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "InnoGames",
    developer: "InnoGames",
    release_date: "2015-04-08",
    freetogame_profile_url: "https://www.freetogame.com/elvenar",
  },
  {
    id: 11,
    title: "Neverwinter",
    thumbnail: "https://www.freetogame.com/g/11/thumbnail.jpg",
    short_description:
      "A free-to-play 3D action MMORPG based on the acclaimed Dungeons & Dragons fantasy roleplaying game. ",
    game_url: "https://www.freetogame.com/open/neverwinter",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Perfect World Entertainment",
    developer: "Cryptic Studios",
    release_date: "2013-12-06",
    freetogame_profile_url: "https://www.freetogame.com/neverwinter",
  },
  {
    id: 380,
    title: "Dark Orbit Reloaded",
    thumbnail: "https://www.freetogame.com/g/380/thumbnail.jpg",
    short_description:
      "A browser-based 3D space-combat MMO with a massive playerbase!",
    game_url: "https://www.freetogame.com/open/darkorbit",
    genre: "Shooter",
    platform: "Web Browser",
    publisher: "Bigpoint",
    developer: "Bigpoint",
    release_date: "2006-12-11",
    freetogame_profile_url: "https://www.freetogame.com/darkorbit",
  },
  {
    id: 515,
    title: "Halo Infinite",
    thumbnail: "https://www.freetogame.com/g/515/thumbnail.jpg",
    short_description:
      "For the first time ever, a free-to-play Halo experience is available in the form of Halo Infinite’s multiplayer.",
    game_url: "https://www.freetogame.com/open/halo-infinite",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Xbox Game Studios",
    developer: "343 Industries",
    release_date: "2021-11-15",
    freetogame_profile_url: "https://www.freetogame.com/halo-infinite",
  },
  {
    id: 573,
    title: "Titan Revenge",
    thumbnail: "https://www.freetogame.com/g/573/thumbnail.jpg",
    short_description:
      "A 3D Norse-themed browser MMORPG developed and published by Game Hollywood Games",
    game_url: "https://www.freetogame.com/open/titan-revenge",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Game Hollywood Games",
    developer: "Game Hollywood Games",
    release_date: "2023-12-20",
    freetogame_profile_url: "https://www.freetogame.com/titan-revenge",
  },
  {
    id: 522,
    title: "Flyff Universe",
    thumbnail: "https://www.freetogame.com/g/522/thumbnail.jpg",
    short_description:
      "Get the full Flyff experience on any platform with the free-to-play browser-based MMORPG Flyff Universe.",
    game_url: "https://www.freetogame.com/open/flyff-universe",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Gala Lab",
    developer: "Gala Lab",
    release_date: "2022-06-14",
    freetogame_profile_url: "https://www.freetogame.com/flyff-universe",
  },
  {
    id: 511,
    title: "Phantasy Star Online 2 New Genesis",
    thumbnail: "https://www.freetogame.com/g/511/thumbnail.jpg",
    short_description:
      "The legacy of Phantasy Star Online 2 continues a thousand years later!",
    game_url: "https://www.freetogame.com/open/pso2-new-genesis",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Sega",
    developer: "Sega",
    release_date: "2021-06-09",
    freetogame_profile_url: "https://www.freetogame.com/pso2-new-genesis",
  },
  {
    id: 455,
    title: "Eternal Fury",
    thumbnail: "https://www.freetogame.com/g/455/thumbnail.jpg",
    short_description: "A free-to-play ARPG from R2 Games!",
    game_url: "https://www.freetogame.com/open/eternal-fury",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "R2 Games",
    developer: "R2 Games",
    release_date: "2019-05-21",
    freetogame_profile_url: "https://www.freetogame.com/eternal-fury",
  },
  {
    id: 5,
    title: "Crossout",
    thumbnail: "https://www.freetogame.com/g/5/thumbnail.jpg",
    short_description: "A post-apocalyptic MMO vehicle combat game! ",
    game_url: "https://www.freetogame.com/open/crossout",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Targem",
    developer: "Gaijin",
    release_date: "2017-05-30",
    freetogame_profile_url: "https://www.freetogame.com/crossout",
  },
  {
    id: 9,
    title: "World of Warships",
    thumbnail: "https://www.freetogame.com/g/9/thumbnail.jpg",
    short_description:
      "A 3D free to play naval action-themed MMO from the creators of World of Tanks! ",
    game_url: "https://www.freetogame.com/open/world-of-warships",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Wargaming",
    developer: "Wargaming",
    release_date: "2015-07-02",
    freetogame_profile_url: "https://www.freetogame.com/world-of-warships",
  },
  {
    id: 12,
    title: "War Thunder",
    thumbnail: "https://www.freetogame.com/g/12/thumbnail.jpg",
    short_description:
      "A MMO shooter that puts you in command of hundreds of the finest combat vehicles of World War II.",
    game_url: "https://www.freetogame.com/open/war-thunder",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Gaijin Entertainment",
    developer: "Gaijin Entertainment",
    release_date: "2013-08-15",
    freetogame_profile_url: "https://www.freetogame.com/war-thunder",
  },
  {
    id: 2,
    title: "World of Tanks",
    thumbnail: "https://www.freetogame.com/g/2/thumbnail.jpg",
    short_description:
      "If you like blowing up tanks, with a quick and intense game style you will love this game!",
    game_url: "https://www.freetogame.com/open/world-of-tanks",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Wargaming",
    developer: "Wargaming",
    release_date: "2011-04-12",
    freetogame_profile_url: "https://www.freetogame.com/world-of-tanks",
  },
  {
    id: 560,
    title: "Palia",
    thumbnail: "https://www.freetogame.com/g/560/thumbnail.jpg",
    short_description: "A cozy MMO with homebuilding and some adventure.",
    game_url: "https://www.freetogame.com/open/palia",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Singularity Six",
    developer: "Singularity Six",
    release_date: "2023-08-10",
    freetogame_profile_url: "https://www.freetogame.com/palia",
  },
  {
    id: 458,
    title: "League of Angels - Heaven's Fury",
    thumbnail: "https://www.freetogame.com/g/458/thumbnail.jpg",
    short_description:
      "A free-to-play, browser-based fantasy online action RPG based loosely on Western mythology!",
    game_url: "https://www.freetogame.com/open/league-of-angels-heavens-fury",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Gtarcade",
    developer: "Yoozoo Games",
    release_date: "2020-01-09",
    freetogame_profile_url:
      "https://www.freetogame.com/league-of-angels-heavens-fury",
  },
  {
    id: 14,
    title: "Star Trek Online",
    thumbnail: "https://www.freetogame.com/g/14/thumbnail.jpg",
    short_description:
      "A free-to-play, 3D, Sci-Fi MMORPG based on the popular Star Trek series.",
    game_url: "https://www.freetogame.com/open/star-trek-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Perfect World Entertainment",
    developer: " Cryptic Studios",
    release_date: "2010-02-02",
    freetogame_profile_url: "https://www.freetogame.com/star-trek-online",
  },
  {
    id: 529,
    title: "Tower of Fantasy",
    thumbnail: "https://www.freetogame.com/g/529/thumbnail.jpg",
    short_description:
      "Tower of Fantasy is a 3D open-world RPG, anime-style sci-fi MMO RPG game with unique characters and beautiful open vistas!",
    game_url: "https://www.freetogame.com/open/tower-of-fantasy",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Level Infinite",
    developer: "Hotta Studio",
    release_date: "2022-08-10",
    freetogame_profile_url: "https://www.freetogame.com/tower-of-fantasy",
  },
  {
    id: 528,
    title: "Noah’s Heart",
    thumbnail: "https://www.freetogame.com/g/528/thumbnail.jpg",
    short_description:
      "Noah’s Heart is an open-world MMORPG game with a focus on exploration and socialization.",
    game_url: "https://www.freetogame.com/open/noahs-heart",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Archosaur Games",
    developer: "Archosaur Games",
    release_date: "2022-07-28",
    freetogame_profile_url: "https://www.freetogame.com/noahs-heart",
  },
  {
    id: 466,
    title: "Valorant",
    thumbnail: "https://www.freetogame.com/g/466/thumbnail.jpg",
    short_description:
      "Test your mettle in Riot Games’ character-based FPS shooter Valorant.",
    game_url: "https://www.freetogame.com/open/valorant",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Riot Games",
    developer: "Riot Games",
    release_date: "2020-06-02",
    freetogame_profile_url: "https://www.freetogame.com/valorant",
  },
  {
    id: 467,
    title: "Phantasy Star Online 2",
    thumbnail: "https://www.freetogame.com/g/467/thumbnail.jpg",
    short_description:
      "Welcome to ARKS, and elite task force searching dangerous planets for the corrupted Falspawn in Phantasy Star 2 Online, Sega’s popular, free-to-play sci-fi MMORPG.",
    game_url: "https://www.freetogame.com/open/pso2",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "SEGA",
    developer: "SEGA",
    release_date: "2020-05-27",
    freetogame_profile_url: "https://www.freetogame.com/pso2",
  },
  {
    id: 452,
    title: "Call Of Duty: Warzone",
    thumbnail: "https://www.freetogame.com/g/452/thumbnail.jpg",
    short_description:
      "A standalone free-to-play battle royale and modes accessible via Call of Duty: Modern Warfare.",
    game_url: "https://www.freetogame.com/open/call-of-duty-warzone",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Activision",
    developer: "Infinity Ward",
    release_date: "2020-03-10",
    freetogame_profile_url: "https://www.freetogame.com/call-of-duty-warzone",
  },
  {
    id: 21,
    title: "Destiny 2",
    thumbnail: "https://www.freetogame.com/g/21/thumbnail.jpg",
    short_description: "A free-to-play multiplayer Sci-Fi MMOFPS from Bungie.",
    game_url: "https://www.freetogame.com/open/destiny-2",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Bungie",
    developer: "Bungie",
    release_date: "2019-10-01",
    freetogame_profile_url: "https://www.freetogame.com/destiny-2",
  },
  {
    id: 1,
    title: "Dauntless",
    thumbnail: "https://www.freetogame.com/g/1/thumbnail.jpg",
    short_description:
      "A free-to-play, co-op action RPG with gameplay similar to Monster Hunter.",
    game_url: "https://www.freetogame.com/open/dauntless",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Phoenix Labs",
    developer: "Phoenix Labs, Iron Galaxy",
    release_date: "2019-05-21",
    freetogame_profile_url: "https://www.freetogame.com/dauntless",
  },
  {
    id: 23,
    title: "Apex Legends",
    thumbnail: "https://www.freetogame.com/g/23/thumbnail.jpg",
    short_description:
      "A free-to-play strategic battle royale game featuring 60-player matches and team-based play. ",
    game_url: "https://www.freetogame.com/open/apex-legends",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Electronic Arts",
    developer: "Electronic Arts",
    release_date: "2019-02-04",
    freetogame_profile_url: "https://www.freetogame.com/apex-legends",
  },
  {
    id: 57,
    title: "Fortnite",
    thumbnail: "https://www.freetogame.com/g/57/thumbnail.jpg",
    short_description:
      "A free-to-play, standalone mode of Epic Game's Fortnite. ",
    game_url: "https://www.freetogame.com/open/fortnite-battle-royale",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Epic Games",
    developer: "Epic Games",
    release_date: "2017-09-26",
    freetogame_profile_url: "https://www.freetogame.com/fortnite-battle-royale",
  },
  {
    id: 449,
    title: "Albion Online",
    thumbnail: "https://www.freetogame.com/g/449/thumbnail.jpg",
    short_description:
      "A free-to-play cross-platform sandbox MMO developed and published by Sandbox Interactive GmbH. ",
    game_url: "https://www.freetogame.com/open/albion-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Sandbox Interactive GmbH",
    developer: "Sandbox Interactive GmbH",
    release_date: "2017-07-17",
    freetogame_profile_url: "https://www.freetogame.com/albion-online",
  },
  {
    id: 6,
    title: "Blade and Soul",
    thumbnail: "https://www.freetogame.com/g/6/thumbnail.jpg",
    short_description:
      "A free-to-play martial arts MMORPG that tasks players with learning combination attacks.",
    game_url: "https://www.freetogame.com/open/blade-and-soul",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "NCSoft",
    developer: "NCSoft",
    release_date: "2016-01-19",
    freetogame_profile_url: "https://www.freetogame.com/blade-and-soul",
  },
  {
    id: 212,
    title: "Brawlhalla",
    thumbnail: "https://www.freetogame.com/g/212/thumbnail.jpg",
    short_description:
      "A free-to-play 2D platform fighter inspired by the Smash Bros.",
    game_url: "https://www.freetogame.com/open/brawlhalla",
    genre: "Fighting",
    platform: "PC (Windows)",
    publisher: "Blue Mammoth Games",
    developer: "Blue Mammoth Games",
    release_date: "2015-11-03",
    freetogame_profile_url: "https://www.freetogame.com/brawlhalla",
  },
  {
    id: 8,
    title: "Trove",
    thumbnail: "https://www.freetogame.com/g/8/thumbnail.jpg",
    short_description:
      "A free to play Sandbox massively multiplayer online role-playing game! ",
    game_url: "https://www.freetogame.com/open/trove",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Trion Worlds",
    developer: "Trion Worlds",
    release_date: "2015-07-09",
    freetogame_profile_url: "https://www.freetogame.com/trove",
  },
  {
    id: 217,
    title: "Smite",
    thumbnail: "https://www.freetogame.com/g/217/thumbnail.jpg",
    short_description:
      "A popular free-to-play 3D MOBA where you take on the role of an ancient god.",
    game_url: "https://www.freetogame.com/open/smite",
    genre: "MOBA",
    platform: "PC (Windows)",
    publisher: "Hi-Rez Studios",
    developer: "Hi-Rez Studios",
    release_date: "2014-03-25",
    freetogame_profile_url: "https://www.freetogame.com/smite",
  },
  {
    id: 3,
    title: "Warframe",
    thumbnail: "https://www.freetogame.com/g/3/thumbnail.jpg",
    short_description:
      "A cooperative free-to-play third person online action shooter set in an stunning sci-fi world. ",
    game_url: "https://www.freetogame.com/open/warframe",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Digital Extremes",
    developer: "Digital Extremes",
    release_date: "2013-03-25",
    freetogame_profile_url: "https://www.freetogame.com/warframe",
  },
  {
    id: 13,
    title: "Guild Wars 2",
    thumbnail: "https://www.freetogame.com/g/13/thumbnail.jpg",
    short_description:
      "A free-to-play MMORPG, the follow-up to ArenaNet's popular Guild Wars. ",
    game_url: "https://www.freetogame.com/open/guild-wars-2",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "NCsoft",
    developer: "ArenaNet",
    release_date: "2012-08-28",
    freetogame_profile_url: "https://www.freetogame.com/guild-wars-2",
  },
  {
    id: 350,
    title: "Goodgame Empire",
    thumbnail: "https://www.freetogame.com/g/350/thumbnail.jpg",
    short_description:
      "A free to play medieval strategy browser game. Build you own castle and create a powerful army! ",
    game_url: "https://www.freetogame.com/open/goodgame-empire",
    genre: "Strategy",
    platform: "Web Browser",
    publisher: "Goodgame Studios",
    developer: "Goodgame Studios",
    release_date: "2011-08-14",
    freetogame_profile_url: "https://www.freetogame.com/goodgame-empire",
  },
  {
    id: 427,
    title: "Drakensang Online",
    thumbnail: "https://www.freetogame.com/g/427/thumbnail.jpg",
    short_description:
      "A free to play browser-based top-down hack-and-slash 3D MMORPG similar to games in the Diablo series.",
    game_url: "https://www.freetogame.com/open/drakensang-online",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Bigpoint",
    developer: "Bigpoint",
    release_date: "2011-08-08",
    freetogame_profile_url: "https://www.freetogame.com/drakensang-online",
  },
  {
    id: 433,
    title: "RuneScape",
    thumbnail: "https://www.freetogame.com/g/433/thumbnail.jpg",
    short_description:
      "A popular 3D browser MMORPG boasting a huge player base and 15 years of content.",
    game_url: "https://www.freetogame.com/open/runescape",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Jagex",
    developer: "Jagex",
    release_date: "2001-01-04",
    freetogame_profile_url: "https://www.freetogame.com/runescape",
  },
  {
    id: 572,
    title: "Ravendawn",
    thumbnail: "https://www.freetogame.com/g/572/thumbnail.jpg",
    short_description:
      "A 2D top-down MMORPG featuring homesteading and building mechanics.",
    game_url: "https://www.freetogame.com/open/ravendawn",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Tavernlight Games",
    developer: "Tavernlight Games",
    release_date: "2024-01-16",
    freetogame_profile_url: "https://www.freetogame.com/ravendawn",
  },
  {
    id: 62,
    title: "Kritika: Zero",
    thumbnail: "https://www.freetogame.com/g/62/thumbnail.jpg",
    short_description:
      "A free-to-play hack-and-slash MMORPG with both a single-player adventure combat from Valofe. ",
    game_url: "https://www.freetogame.com/open/kritika",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Valofe",
    developer: "Valofe",
    release_date: "2024-01-25",
    freetogame_profile_url: "https://www.freetogame.com/kritika",
  },
  {
    id: 575,
    title: "One Punch Man: World",
    thumbnail: "https://www.freetogame.com/g/575/thumbnail.jpg",
    short_description:
      "A free-to-play multiplayer 3D action game from Crunchyroll Games.",
    game_url: "https://www.freetogame.com/open/one-punch-man-world",
    genre: "Action Game",
    platform: "PC (Windows)",
    publisher: "Perfect World Games",
    developer: "Crunchyroll",
    release_date: "2024-01-31",
    freetogame_profile_url: "https://www.freetogame.com/one-punch-man-world",
  },
  {
    id: 576,
    title: "Battle Teams 2",
    thumbnail: "https://www.freetogame.com/g/576/thumbnail.jpg",
    short_description:
      "A multiplayer tactical shooter with an Eastern aesthetic.",
    game_url: "https://www.freetogame.com/open/battle-teams-2",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Wizard Games Global",
    developer: "Wizard Games Global",
    release_date: "2024-01-31",
    freetogame_profile_url: "https://www.freetogame.com/battle-teams-2",
  },
  {
    id: 570,
    title: "The Finals",
    thumbnail: "https://www.freetogame.com/g/570/thumbnail.jpg",
    short_description: "A game-show style PvP shooter from Embark Studios.",
    game_url: "https://www.freetogame.com/open/the-finals",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Embark Studios",
    developer: "Embark Studios",
    release_date: "2023-12-07",
    freetogame_profile_url: "https://www.freetogame.com/the-finals",
  },
  {
    id: 571,
    title: "Infinite Borders",
    thumbnail: "https://www.freetogame.com/g/571/thumbnail.jpg",
    short_description:
      "A free-to-play strategy game from NetEase set during China’s Three Kingdoms period.",
    game_url: "https://www.freetogame.com/open/infinite-borders",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "NetEase Games",
    developer: "NetEase Games",
    release_date: "2023-12-22",
    freetogame_profile_url: "https://www.freetogame.com/infinite-borders",
  },
  {
    id: 569,
    title: "Destiny's Divide",
    thumbnail: "https://www.freetogame.com/g/569/thumbnail.jpg",
    short_description:
      "Free-to-play PvP Fantasy Card Game for competitive card game players.",
    game_url: "https://www.freetogame.com/open/destinys-divide",
    genre: "Card",
    platform: "PC (Windows)",
    publisher: "Fobia",
    developer: "Fobia",
    release_date: "2023-11-03",
    freetogame_profile_url: "https://www.freetogame.com/destinys-divide",
  },
  {
    id: 568,
    title: "Warhammer 40,000: Warpforge",
    thumbnail: "https://www.freetogame.com/g/568/thumbnail.jpg",
    short_description: "A free-to-play CCG set in the Warhammer 40K universe.",
    game_url: "https://www.freetogame.com/open/warhammer-40000-warpforge",
    genre: "Card",
    platform: "PC (Windows)",
    publisher: "Everguild Ltd.",
    developer: "Everguild Ltd.",
    release_date: "2023-10-19",
    freetogame_profile_url:
      "https://www.freetogame.com/warhammer-40000-warpforge",
  },
  {
    id: 564,
    title: "Synced",
    thumbnail: "https://www.freetogame.com/g/564/thumbnail.jpg",
    short_description: "A free-to-play co-op sci-fi shooter.",
    game_url: "https://www.freetogame.com/open/synced",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Level Infinite",
    developer: "NExT Studios",
    release_date: "2023-09-07",
    freetogame_profile_url: "https://www.freetogame.com/synced",
  },
  {
    id: 565,
    title: "Warhaven",
    thumbnail: "https://www.freetogame.com/g/565/thumbnail.jpg",
    short_description: "A free-to-play, medieval fantasy PvP game from Nexon.",
    game_url: "https://www.freetogame.com/open/warhaven",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Nexon",
    developer: "Nexon",
    release_date: "2023-09-20",
    freetogame_profile_url: "https://www.freetogame.com/warhaven",
  },
  {
    id: 567,
    title: "Microvolts: Recharged",
    thumbnail: "https://www.freetogame.com/g/567/thumbnail.jpg",
    short_description: "A lobby-based third-person shooter with a toy-theme.",
    game_url: "https://www.freetogame.com/open/microvolts",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Masangsoft",
    developer: "Masangsoft",
    release_date: "2023-09-08",
    freetogame_profile_url: "https://www.freetogame.com/microvolts",
  },
  {
    id: 558,
    title: "Hawked",
    thumbnail: "https://www.freetogame.com/g/558/thumbnail.jpg",
    short_description: "A free-to-play PvPvE treasure hunting shooter.",
    game_url: "https://www.freetogame.com/open/hawked",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "My.Games",
    developer: "My.Games",
    release_date: "2023-08-03",
    freetogame_profile_url: "https://www.freetogame.com/hawked",
  },
  {
    id: 559,
    title: "Tales Of Yore",
    thumbnail: "https://www.freetogame.com/g/559/thumbnail.jpg",
    short_description: "A 2D MMORPG with lots of RPG tropes.",
    game_url: "https://www.freetogame.com/open/tales-of-yore",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Coke And Code",
    developer: "Coke And Code",
    release_date: "2023-08-08",
    freetogame_profile_url: "https://www.freetogame.com/tales-of-yore",
  },
  {
    id: 562,
    title: "Waven",
    thumbnail: "https://www.freetogame.com/g/562/thumbnail.jpg",
    short_description: "A free-to-play online tactical RPG from Ankama.",
    game_url: "https://www.freetogame.com/open/waven",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Ankama Studio",
    developer: "Ankama Games",
    release_date: "2023-08-16",
    freetogame_profile_url: "https://www.freetogame.com/waven",
  },
  {
    id: 566,
    title: "Town of Salem 2",
    thumbnail: "https://www.freetogame.com/g/566/thumbnail.jpg",
    short_description: "A deduction game set in Salem.",
    game_url: "https://www.freetogame.com/open/town-of-salem-2",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "BlankMediaGames LLC",
    developer: "BlankMediaGames LLC",
    release_date: "2023-08-25",
    freetogame_profile_url: "https://www.freetogame.com/town-of-salem-2",
  },
  {
    id: 556,
    title: "Naraka: Bladepoint",
    thumbnail: "https://www.freetogame.com/g/556/thumbnail.jpg",
    short_description: "A free-to-play melee focused battle royale.",
    game_url: "https://www.freetogame.com/open/naraka-bladepoint",
    genre: "Battle Royale",
    platform: "PC (Windows)",
    publisher: "24 Entertainment",
    developer: "NetEase",
    release_date: "2023-07-13",
    freetogame_profile_url: "https://www.freetogame.com/naraka-bladepoint",
  },
  {
    id: 554,
    title: "Undawn",
    thumbnail: "https://www.freetogame.com/g/554/thumbnail.jpg",
    short_description:
      "A free-to-play open-world survival RPG developed by LightSpeed studios and published by Level Infinite.",
    game_url: "https://www.freetogame.com/open/undawn",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Level Infinite",
    developer: "LightSpeed Studios",
    release_date: "2023-06-15",
    freetogame_profile_url: "https://www.freetogame.com/undawn",
  },
  {
    id: 268,
    title: "Eden Eternal",
    thumbnail: "https://www.freetogame.com/g/268/thumbnail.jpg",
    short_description:
      "A free to play fantasy MMORPG with cute anime-inspired graphics.",
    game_url: "https://www.freetogame.com/open/eden-eternal",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "X-Legend Entertainment",
    developer: "X-Legend Entertainment",
    release_date: "2023-05-10",
    freetogame_profile_url: "https://www.freetogame.com/eden-eternal",
  },
  {
    id: 551,
    title: "Veiled Experts",
    thumbnail: "https://www.freetogame.com/g/551/thumbnail.jpg",
    short_description:
      "A free-to-play multiplayer shooter game focused on the search and destroy mode of classic shooters.",
    game_url: "https://www.freetogame.com/open/veiled-experts",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Nexon Games Co., LTC",
    developer: "Nexon",
    release_date: "2023-05-18",
    freetogame_profile_url: "https://www.freetogame.com/veiled-experts",
  },
  {
    id: 552,
    title: "Jected - Rivals",
    thumbnail: "https://www.freetogame.com/g/552/thumbnail.jpg",
    short_description:
      "A free-to-play game mixing extreme sports with destructible vehicles and a unique ejection mechanic.",
    game_url: "https://www.freetogame.com/open/jected-rivals",
    genre: "Sports",
    platform: "PC (Windows)",
    publisher: "THQ Nordic",
    developer: "PowWow Entertainment",
    release_date: "2023-05-04",
    freetogame_profile_url: "https://www.freetogame.com/jected-rivals",
  },
  {
    id: 557,
    title: "Ethyrial: Echoes of Yore",
    thumbnail: "https://www.freetogame.com/g/557/thumbnail.jpg",
    short_description:
      "A old-school MMORPG set in a world on the brink of Civil War",
    game_url: "https://www.freetogame.com/open/ethyrial-echoes-of-yore",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: " Gellyberry Studios",
    developer: " Gellyberry Studios",
    release_date: "2023-05-01",
    freetogame_profile_url:
      "https://www.freetogame.com/ethyrial-echoes-of-yore",
  },
  {
    id: 574,
    title: "Mad World",
    thumbnail: "https://www.freetogame.com/g/574/thumbnail.jpg",
    short_description:
      "A free-to-play Browser MMORPG from Jandisoft with a unique theme and art style.",
    game_url: "https://www.freetogame.com/open/mad-world",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Jandisoft",
    developer: "Jandisoft",
    release_date: "2023-04-10",
    freetogame_profile_url: "https://www.freetogame.com/mad-world",
  },
  {
    id: 548,
    title: "Dead Cide Club",
    thumbnail: "https://www.freetogame.com/g/548/thumbnail.jpg",
    short_description:
      "A free-to-play, side-scrolling shooter with a variety of modes and character types to choose from.",
    game_url: "https://www.freetogame.com/open/dead-cide-club",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "PressA",
    developer: "PressZ",
    release_date: "2023-02-28",
    freetogame_profile_url: "https://www.freetogame.com/dead-cide-club",
  },
  {
    id: 546,
    title: "Kartrider: Drift",
    thumbnail: "https://www.freetogame.com/g/546/thumbnail.jpg",
    short_description:
      "A free-to-play multiplayer online racing game set in the Kartrider franchise.",
    game_url: "https://www.freetogame.com/open/kartrider-drift",
    genre: "Racing",
    platform: "PC (Windows)",
    publisher: "Nexon America Inc.",
    developer: "Nexon Korea Corporation",
    release_date: "2023-01-10",
    freetogame_profile_url: "https://www.freetogame.com/kartrider-drift",
  },
  {
    id: 547,
    title: "Warlander",
    thumbnail: "https://www.freetogame.com/g/547/thumbnail.jpg",
    short_description:
      "A medieval-style combat game with a selection of modes and characters.",
    game_url: "https://www.freetogame.com/open/warlander",
    genre: "MOBA",
    platform: "PC (Windows)",
    publisher: "Plaion",
    developer: "Toylogic Inc.",
    release_date: "2023-01-24",
    freetogame_profile_url: "https://www.freetogame.com/warlander",
  },
  {
    id: 545,
    title: "Fangs",
    thumbnail: "https://www.freetogame.com/g/545/thumbnail.jpg",
    short_description: "A 4v4 MOBA with hero-specific strategies.",
    game_url: "https://www.freetogame.com/open/fangs",
    genre: "MOBA",
    platform: "PC (Windows)",
    publisher: "Hidden Leaf Games",
    developer: "Hidden Leaf Games",
    release_date: "2022-11-30",
    freetogame_profile_url: "https://www.freetogame.com/fangs",
  },
  {
    id: 549,
    title: "Summoners War: Chronicles",
    thumbnail: "https://www.freetogame.com/g/549/thumbnail.jpg",
    short_description:
      "A multi-platform ARPG set in the Summoners War universe.",
    game_url: "https://www.freetogame.com/open/summoners-war-chronicles",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Com2uS",
    developer: "Com2uS",
    release_date: "2022-11-09",
    freetogame_profile_url:
      "https://www.freetogame.com/summoners-war-chronicles",
  },
  {
    id: 541,
    title: "Marvel Snap",
    thumbnail: "https://www.freetogame.com/g/541/thumbnail.jpg",
    short_description:
      "A fast paced strategy card game set in the Marvel universe.",
    game_url: "https://www.freetogame.com/open/marvel-snap",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Nuverse",
    developer: "Second Dinner Studios, Inc.",
    release_date: "2022-10-18",
    freetogame_profile_url: "https://www.freetogame.com/marvel-snap",
  },
  {
    id: 542,
    title: "World Boss",
    thumbnail: "https://www.freetogame.com/g/542/thumbnail.jpg",
    short_description:
      "An experimental FPS based on io and roguelike gameplay.",
    game_url: "https://www.freetogame.com/open/world-boss",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Playside",
    developer: "Playside",
    release_date: "2022-10-19",
    freetogame_profile_url: "https://www.freetogame.com/world-boss",
  },
  {
    id: 536,
    title: "Omega Strikers",
    thumbnail: "https://www.freetogame.com/g/536/thumbnail.jpg",
    short_description: "A 3v3 socccer-style game with knockouts.",
    game_url: "https://www.freetogame.com/open/omega-strikers",
    genre: "Sports",
    platform: "PC (Windows)",
    publisher: "Odyssey Interactive",
    developer: "Odyssey Interactive",
    release_date: "2022-09-16",
    freetogame_profile_url: "https://www.freetogame.com/omega-strikers",
  },
  {
    id: 537,
    title: "Gundam Evolution",
    thumbnail: "https://www.freetogame.com/g/537/thumbnail.jpg",
    short_description:
      "A 6v6 team-based shooter based on the Gundam multiverse",
    game_url: "https://www.freetogame.com/open/gundam-evolution",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Bandai Namco",
    developer: "Bandai Namco",
    release_date: "2022-09-21",
    freetogame_profile_url: "https://www.freetogame.com/gundam-evolution",
  },
  {
    id: 539,
    title: "Deathverse: Let It Die",
    thumbnail: "https://www.freetogame.com/g/539/thumbnail.jpg",
    short_description:
      "A game of survival where contestants are pit against each other in a life or death game show.",
    game_url: "https://www.freetogame.com/open/deathverse-let-it-die",
    genre: "Battle Royale",
    platform: "PC (Windows)",
    publisher: "Supertrick Games, Inc.",
    developer: "GungHo Online Entertianment, Inc.",
    release_date: "2022-09-28",
    freetogame_profile_url: "https://www.freetogame.com/deathverse-let-it-die",
  },
  {
    id: 544,
    title: "Galahad 3093",
    thumbnail: "https://www.freetogame.com/g/544/thumbnail.jpg",
    short_description:
      "A 12v12 team shooter featuring mechs based on Arthurian legend.",
    game_url: "https://www.freetogame.com/open/galahad-3093",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Simutronics Corp.",
    developer: "Simutronics Corp.",
    release_date: "2022-09-01",
    freetogame_profile_url: "https://www.freetogame.com/galahad-3093",
  },
  {
    id: 527,
    title: "Aero Tales Online",
    thumbnail: "https://www.freetogame.com/g/527/thumbnail.jpg",
    short_description:
      "Aero Tales Online: The World is a free-to-play 3D anime-style MMORPG with PvP and PvE elements. The game revolves around the “mysterious story of the Key of Skylight”.",
    game_url: "https://www.freetogame.com/open/aero-tales-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Anisage Games",
    developer: "Anisage Games",
    release_date: "2022-08-01",
    freetogame_profile_url: "https://www.freetogame.com/aero-tales-online",
  },
  {
    id: 531,
    title: "Magic Spellslingers",
    thumbnail: "https://www.freetogame.com/g/531/thumbnail.jpg",
    short_description:
      "Magic Spellslingers is the latest entry based on Witzards of the Coast’s popular card game Magic: The Gathering.",
    game_url: "https://www.freetogame.com/open/magic-spellslingers",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Wizards of the Coast LLC",
    developer: "Pipeworks Studios, Seismic Games",
    release_date: "2022-08-05",
    freetogame_profile_url: "https://www.freetogame.com/magic-spellslingers",
  },
  {
    id: 533,
    title: "A.V.A Global",
    thumbnail: "https://www.freetogame.com/g/533/thumbnail.jpg",
    short_description:
      "A.V.A is a free-to-play online first-person shooter with multiple game modes, unique customizations, as well as PvP and PvE gameplay.",
    game_url: "https://www.freetogame.com/open/ava",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "NEOWIZ",
    developer: "NEOWIZ",
    release_date: "2022-08-24",
    freetogame_profile_url: "https://www.freetogame.com/ava",
  },
  {
    id: 534,
    title: "Lost Light",
    thumbnail: "https://www.freetogame.com/g/534/thumbnail.jpg",
    short_description:
      "A post-apocalyptic shooter built around creating a realistic experience.",
    game_url: "https://www.freetogame.com/open/lost-light",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "NetEase Games",
    developer: "NetEase Games",
    release_date: "2022-08-04",
    freetogame_profile_url: "https://www.freetogame.com/lost-light",
  },
  {
    id: 524,
    title: "Temperia: Soul of Majestic",
    thumbnail: "https://www.freetogame.com/g/524/thumbnail.jpg",
    short_description:
      "Fans of collectible card games, are you looking for something a bit different from the normal fare? Then a peek at Moonwolf Entertainment and A2 Softworks’ Temperia: Soul of Majestic might be in order.",
    game_url: "https://www.freetogame.com/open/temperia",
    genre: "Card Game",
    platform: "PC (Windows)",
    publisher: "Leonardo Interactive",
    developer: "MoonWolf Entertainment, A2 Softworks",
    release_date: "2022-07-26",
    freetogame_profile_url: "https://www.freetogame.com/temperia",
  },
  {
    id: 526,
    title: "Chimeraland",
    thumbnail: "https://www.freetogame.com/g/526/thumbnail.jpg",
    short_description:
      "Explore the open-world sandbox MMO game set in a mythical world. Play as one of a large number of races, from jelly-fish to dragon-person – or even a regular old human if that’s your thing. Explore the land, gather resources, craft items, build homes and more.",
    game_url: "https://www.freetogame.com/open/chimeraland",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Level Infinite",
    developer: "Pixel soft",
    release_date: "2022-07-14",
    freetogame_profile_url: "https://www.freetogame.com/chimeraland",
  },
  {
    id: 532,
    title: "World of Runes",
    thumbnail: "https://www.freetogame.com/g/532/thumbnail.jpg",
    short_description:
      "An adorable anime-style MMO featuring cute pets and collectable cards.",
    game_url: "https://www.freetogame.com/open/world-of-runes",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "F5 Game Company Limited",
    developer: "R2 Games",
    release_date: "2022-06-13",
    freetogame_profile_url: "https://www.freetogame.com/world-of-runes",
  },
  {
    id: 520,
    title: "Roller Champions",
    thumbnail: "https://www.freetogame.com/g/520/thumbnail.jpg",
    short_description:
      "What if you could player roller derby, but in a more organized and less physically dangerous environment?",
    game_url: "https://www.freetogame.com/open/roller-champions",
    genre: "Sports",
    platform: "PC (Windows)",
    publisher: "Ubisoft",
    developer: "Ubisoft",
    release_date: "2022-05-25",
    freetogame_profile_url: "https://www.freetogame.com/roller-champions",
  },
  {
    id: 519,
    title: "Space Punks",
    thumbnail: "https://www.freetogame.com/g/519/thumbnail.jpg",
    short_description:
      "Space Punks is a sci-fi co-op looter shooter with graphics and humor that will likely appeal to the Borderlands fans among us.",
    game_url: "https://www.freetogame.com/open/space-punks",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "JAGEX",
    developer: "Flying Wild Hog",
    release_date: "2022-04-20",
    freetogame_profile_url: "https://www.freetogame.com/space-punks",
  },
  {
    id: 550,
    title: "Goose, Goose, DUCK",
    thumbnail: "https://www.freetogame.com/g/550/thumbnail.jpg",
    short_description: "A social deduction game with geese.",
    game_url: "https://www.freetogame.com/open/goose-goose-duck",
    genre: "Strategy",
    platform: "PC (Windows)",
    publisher: "Gaggle Studios, Inc.",
    developer: "Gaggle Studios, Inc.",
    release_date: "2021-10-03",
    freetogame_profile_url: "https://www.freetogame.com/goose-goose-duck",
  },
  {
    id: 518,
    title: "Swords of Legends Online",
    thumbnail: "https://www.freetogame.com/g/518/thumbnail.jpg",
    short_description:
      "Explore a fantasy world based on Chinese mythology in Gameforge’s action MMORPG Swords of Legends Online!",
    game_url: "https://www.freetogame.com/open/swords-of-legends-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Gameforge",
    developer: "Wangyuan Shengtang Entertainment",
    release_date: "2021-07-09",
    freetogame_profile_url:
      "https://www.freetogame.com/swords-of-legends-online",
  },
  {
    id: 513,
    title: "Super Squad",
    thumbnail: "https://www.freetogame.com/g/513/thumbnail.jpg",
    short_description:
      "Prepare yourself. It’s time for Mayhem. Super Squad is a multi-player online shoot-’em-up (or MOSH)!",
    game_url: "https://www.freetogame.com/open/super-squad",
    genre: "MOBA",
    platform: "PC (Windows)",
    publisher: "Bad Fox Studios",
    developer: "Bad Fox Studios",
    release_date: "2021-06-25",
    freetogame_profile_url: "https://www.freetogame.com/super-squad",
  },
  {
    id: 328,
    title: "Dofus",
    thumbnail: "https://www.freetogame.com/g/328/thumbnail.jpg",
    short_description:
      "A 2D MMORPG with tons of different classes and a tactical combat system.",
    game_url: "https://www.freetogame.com/open/dofus",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Ankama Games",
    developer: "Ankama Games",
    release_date: "2004-09-01",
    freetogame_profile_url: "https://www.freetogame.com/dofus",
  },
  {
    id: 190,
    title: "Ryzom",
    thumbnail: "https://www.freetogame.com/g/190/thumbnail.jpg",
    short_description:
      "An MMORPG where players are immersed in a massive sandbox world.",
    game_url: "https://www.freetogame.com/open/ryzom",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Winch Gate",
    developer: "Nevrax",
    release_date: "2004-09-19",
    freetogame_profile_url: "https://www.freetogame.com/ryzom",
  },
  {
    id: 329,
    title: "Kal Online",
    thumbnail: "https://www.freetogame.com/g/329/thumbnail.jpg",
    short_description: "A Korean Fantasy MMORPG developed by Inixsoft.",
    game_url: "https://www.freetogame.com/open/kalonline",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Inisxoft",
    developer: "Inisxoft",
    release_date: "2004-06-11",
    freetogame_profile_url: "https://www.freetogame.com/kalonline",
  },
  {
    id: 330,
    title: "Lineage 2",
    thumbnail: "https://www.freetogame.com/g/330/thumbnail.jpg",
    short_description: "A 3D fantasy MMORPG with a strong emphasis on PvP.",
    game_url: "https://www.freetogame.com/open/lineage-2",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "NCSoft",
    developer: "NCSoft",
    release_date: "2004-04-27",
    freetogame_profile_url: "https://www.freetogame.com/lineage-2",
  },
  {
    id: 332,
    title: "Red Stone Online",
    thumbnail: "https://www.freetogame.com/g/332/thumbnail.jpg",
    short_description:
      "A free to play 2D old school isometric MMORPG similar to Diablo.",
    game_url: "https://www.freetogame.com/open/red-stone-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "L＆K CO., LTD",
    developer: "L＆K CO., LTD",
    release_date: "2003-10-06",
    freetogame_profile_url: "https://www.freetogame.com/red-stone-online",
  },
  {
    id: 334,
    title: "Mu Online",
    thumbnail: "https://www.freetogame.com/g/334/thumbnail.jpg",
    short_description: "A free to play Dungeon Crawler game like Diablo!",
    game_url: "https://www.freetogame.com/open/mu-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Webzen",
    developer: "Webzen",
    release_date: "2003-10-06",
    freetogame_profile_url: "https://www.freetogame.com/mu-online",
  },
  {
    id: 18,
    title: "Second Life",
    thumbnail: "https://www.freetogame.com/g/18/thumbnail.jpg",
    short_description:
      "A free to play 3D online virtual world with a huge reputation! ",
    game_url: "https://www.freetogame.com/open/second-life",
    genre: "Social",
    platform: "PC (Windows)",
    publisher: "Linden Lab",
    developer: "Linden Lab",
    release_date: "2003-06-23",
    freetogame_profile_url: "https://www.freetogame.com/second-life",
  },
  {
    id: 335,
    title: "Ragnarok Online",
    thumbnail: "https://www.freetogame.com/g/335/thumbnail.jpg",
    short_description:
      "A popular fantasy MMORPG, back to the golden age of MMORPGs.",
    game_url: "https://www.freetogame.com/open/ragnarok-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Gravity Interactive ",
    developer: "Gravity Interactive ",
    release_date: "2003-06-01",
    freetogame_profile_url: "https://www.freetogame.com/ragnarok-online",
  },
  {
    id: 17,
    title: "Entropia Universe",
    thumbnail: "https://www.freetogame.com/g/17/thumbnail.jpg",
    short_description:
      "A 3D MMO Multi Virtual World Real Cash Economy Experience with RPG elements. ",
    game_url: "https://www.freetogame.com/open/entropia-universe",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "MindArk",
    developer: "MindArk",
    release_date: "2003-01-30",
    freetogame_profile_url: "https://www.freetogame.com/entropia-universe",
  },
  {
    id: 432,
    title: "Habbo",
    thumbnail: "https://www.freetogame.com/g/432/thumbnail.jpg",
    short_description: "One of the largest and most popular Social MMO.",
    game_url: "https://www.freetogame.com/open/habbo",
    genre: "Social",
    platform: "Web Browser",
    publisher: "Sulake Corporation",
    developer: "Sulake Corporation",
    release_date: "2001-09-26",
    freetogame_profile_url: "https://www.freetogame.com/habbo",
  },
  {
    id: 336,
    title: "Anarchy Online",
    thumbnail: "https://www.freetogame.com/g/336/thumbnail.jpg",
    short_description:
      "A free to play Sci-Fi MMO that has withstood the test of time.",
    game_url: "https://www.freetogame.com/open/anarchy-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Funcom",
    developer: "Funcom",
    release_date: "2001-06-27",
    freetogame_profile_url: "https://www.freetogame.com/anarchy-online",
  },
  {
    id: 251,
    title: "The Lord of the Rings Online",
    thumbnail: "https://www.freetogame.com/g/251/thumbnail.jpg",
    short_description:
      "A free to play MMORPG set in the world of J.R.R. Tolkien's \r\nclassic fantasy saga.",
    game_url: "https://www.freetogame.com/open/lotro",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Warner Bros. Interactive Entertainment",
    developer: "Turbine, Inc.",
    release_date: "2001-04-24",
    freetogame_profile_url: "https://www.freetogame.com/lotro",
  },
  {
    id: 339,
    title: "Tibia",
    thumbnail: "https://www.freetogame.com/g/339/thumbnail.jpg",
    short_description:
      "A old-school free-to-play massively multiplayer online \r\nrole-playing game.",
    game_url: "https://www.freetogame.com/open/tibia",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "CipSoft",
    developer: "CipSoft",
    release_date: "1997-01-07",
    freetogame_profile_url: "https://www.freetogame.com/tibia",
  },
];
